[[constraint]]
  name = "github.com/akamai/AkamaiOPEN-edgegrid-golang"
#  branch = "master"
  version = "0.9.3"

[[constraint]]
  branch = "master"
  name = "github.com/akamai/cli-common-golang"

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
#  branch = "master"
  version = "0.0.1"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[prune]
  go-tests = true
  unused-packages = true
